-- TEXTO QUE USE PARA HACER PRUEBAS JSJSJ/*
DROP TABLE INSTRUCCION CASCADE CONSTRAINTS;
DROP TABLE PLATILLO_INGREDIENTE CASCADE CONSTRAINTS;
DROP TABLE INGREDIENTES CASCADE CONSTRAINTS;
DROP TABLE PLATILLO CASCADE CONSTRAINTS;
DROP SEQUENCE sq_id_platillo;
DROP SEQUENCE sq_id_ingrediente;
DROP SEQUENCE sq_folio_pi;
DROP SEQUENCE sq_id_instruccion;
*/

-- CREACION DE SECUENCIAS Y TABLAS
CREATE SEQUENCE sq_id_platillo START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE sq_id_ingrediente START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE sq_folio_pi START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE sq_id_instruccion START WITH 1 INCREMENT BY 1;

CREATE TABLE PLATILLO (
    id_platillo NUMBER PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    porciones NUMBER
);

CREATE TABLE INGREDIENTES (
    id_ingrediente NUMBER PRIMARY KEY,
    nombre_ingrediente VARCHAR2(100) NOT NULL,
    unidad_medida VARCHAR2(50),
    presentacion VARCHAR2(150),
    observacion VARCHAR2(250)
);

CREATE UNIQUE INDEX ix_nombre_ingrediente ON INGREDIENTES(nombre_ingrediente);

CREATE TABLE PLATILLO_INGREDIENTE (
    folio_pi NUMBER PRIMARY KEY,
    id_platillo NUMBER NOT NULL,
    id_ingrediente NUMBER NOT NULL,
    cantidad NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_pi_platillo FOREIGN KEY (id_platillo) REFERENCES PLATILLO(id_platillo),
    CONSTRAINT fk_pi_ingrediente FOREIGN KEY (id_ingrediente) REFERENCES INGREDIENTES(id_ingrediente)
);

CREATE TABLE INSTRUCCION (
    id_instruccion NUMBER PRIMARY KEY,
    id_platillo NUMBER NOT NULL,
    numero_paso NUMBER NOT NULL,
    instruccion VARCHAR2(500) NOT NULL,
    detalle_instruccion VARCHAR2(500),
    CONSTRAINT fk_inst_platillo FOREIGN KEY (id_platillo) REFERENCES PLATILLO(id_platillo)
);

-- CREACION DE OBJETOS PL/SQL (Funcion y Procedimiento)
CREATE OR REPLACE FUNCTION platilloingrediente (platillo platillo.id_platillo%TYPE) 
RETURN NUMBER IS
    contador_ingrediente NUMBER;
BEGIN
    SELECT COUNT(1)
    INTO contador_ingrediente
    FROM platillo_ingrediente
    WHERE id_platillo = platillo;
    
    RETURN contador_ingrediente;
END;
/

CREATE OR REPLACE PROCEDURE inserta_paso_receta(
    pid_platillo IN NUMBER,
    pnumero_paso IN NUMBER,
    pinstruccion IN VARCHAR2,
    pdetalle_instruccion IN VARCHAR2)
IS
BEGIN
    INSERT INTO INSTRUCCION(
        id_instruccion,
        id_platillo,
        numero_paso,
        instruccion,
        detalle_instruccion)
    VALUES(
        sq_id_instruccion.nextval,
        pid_platillo,
        pnumero_paso,
        pinstruccion,
        pdetalle_instruccion);
END;
/

-- INSERCION DE CATALOGOS (Platillos e Ingredientes)
INSERT INTO PLATILLO VALUES (sq_id_platillo.nextval, 'BROCHETA DE RES', 4);
INSERT INTO PLATILLO VALUES (sq_id_platillo.nextval, 'CHILES RELLENOS DE QUESO', 4);
INSERT INTO PLATILLO VALUES (sq_id_platillo.nextval, 'FILETE MIGNON CON CHAMPINONES', 6);
INSERT INTO PLATILLO VALUES (sq_id_platillo.nextval, 'PESCADO AL VAPOR', 4);
INSERT INTO PLATILLO VALUES (sq_id_platillo.nextval, 'POLLO A LA CERVEZA', 4);

INSERT INTO INGREDIENTES VALUES (sq_id_ingrediente.nextval, 'MANTEQUILLA', 'GRAMOS', 'BARRA DE 90 GRAMOS', 'MANTEQUILLA, NO MARGARINA');
INSERT INTO INGREDIENTES VALUES (sq_id_ingrediente.nextval, 'PECHUGA DE POLLO SIN PIEL', 'PIEZAS', 'PIEZA DE PECHUGA', 'PRESENTACION SIN PIEL');
INSERT INTO INGREDIENTES VALUES (sq_id_ingrediente.nextval, 'CERVEZA', 'MILILITROS', 'LATA DE 355 ML', 'MODELO ESPECIAL');
INSERT INTO INGREDIENTES VALUES (sq_id_ingrediente.nextval, 'QUESO COTIJA', 'GRAMOS', 'PRESENTACION 300 GRAMOS', 'QUESO COTIJA DEL PARRAL');
INSERT INTO INGREDIENTES VALUES (sq_id_ingrediente.nextval, 'HUEVO', 'PIEZAS', 'PIEZA', 'UNIDAD DE MEDIDA POR PIEZA');
INSERT INTO INGREDIENTES VALUES (sq_id_ingrediente.nextval, 'ACEITE DE COCINA', 'MILILITROS', 'PRESENTACION 750 ML', 'CUCHARADA 5 ML');
INSERT INTO INGREDIENTES VALUES (sq_id_ingrediente.nextval, 'CHILE MORRON', 'PIEZAS', 'PRESENTACION POR PIEZA', 'TAMBIEN CONOCIDO COMO PIMIENTO');
INSERT INTO INGREDIENTES VALUES (sq_id_ingrediente.nextval, 'OREGANO', 'GRAMOS', 'GRANEL', 'CUCHARADITA CAFETERA DE 1 G');
INSERT INTO INGREDIENTES VALUES (sq_id_ingrediente.nextval, 'CEBOLLA BLANCA', 'PIEZAS', 'PRESENTACION POR PIEZA', '-');
INSERT INTO INGREDIENTES VALUES (sq_id_ingrediente.nextval, 'ACEITUNAS', 'GRAMOS', 'PRESENTACION 175 GRAMOS', 'SIN HUESO');
INSERT INTO INGREDIENTES VALUES (sq_id_ingrediente.nextval, 'FILETE DE RES', 'GRAMOS', 'PRESENTACION GRANEL', 'PRESENTACION BASE 1000 GRAMOS');
INSERT INTO INGREDIENTES VALUES (sq_id_ingrediente.nextval, 'TOCINO', 'GRAMOS', 'PRESENTACION GRANEL', 'PRESENTACION BASE 1000 GRAMOS');
INSERT INTO INGREDIENTES VALUES (sq_id_ingrediente.nextval, 'CHAMPINONES', 'GRAMOS', 'PRESENTACION LATA 100 GRAMOS DRENADO', '-');
INSERT INTO INGREDIENTES VALUES (sq_id_ingrediente.nextval, 'MAIZENA', 'GRAMOS', 'PRESENTACION 425 GRAMOS', 'FECULA DE MAIZ');
INSERT INTO INGREDIENTES VALUES (sq_id_ingrediente.nextval, 'PINIA', 'REBANADAS', 'PRESENTACION POR PIEZA', 'PINA NATURAL O EN ALMIBAR');
INSERT INTO INGREDIENTES VALUES (sq_id_ingrediente.nextval, 'TOMATE', 'PIEZAS', 'PRESENTACION POR PIEZA', 'TOMATE ROJO O SALADETTE');
INSERT INTO INGREDIENTES VALUES (sq_id_ingrediente.nextval, 'PALITOS PARA BROCHETA', 'PIEZAS', 'PAQUETE DE MADERA', 'PALITOS LARGOS');
INSERT INTO INGREDIENTES VALUES (sq_id_ingrediente.nextval, 'PIMIENTA', 'GRAMOS', 'GRANEL', 'PIMIENTA NEGRA MOLIDA');
INSERT INTO INGREDIENTES VALUES (sq_id_ingrediente.nextval, 'SAL', 'GRAMOS', 'GRANEL', 'SAL DE MESA O DE GRANO');
INSERT INTO INGREDIENTES VALUES (sq_id_ingrediente.nextval, 'CHILES PARA RELLENAR', 'PIEZAS', 'PRESENTACION POR PIEZA', 'CHILE POBLANO O PASILLA');
INSERT INTO INGREDIENTES VALUES (sq_id_ingrediente.nextval, 'HARINA', 'GRAMOS', 'GRANEL', 'HARINA DE TRIGO TODO USO');
INSERT INTO INGREDIENTES VALUES (sq_id_ingrediente.nextval, 'CONSOME DE POLLO', 'PIEZAS', 'CUADRITO O CUBITO', 'CONCENTRADO DE POLLO');
INSERT INTO INGREDIENTES VALUES (sq_id_ingrediente.nextval, 'BOTETE CHICO', 'GRAMOS', 'PRESENTACION GRANEL', 'PESCADO BLANCO');
INSERT INTO INGREDIENTES VALUES (sq_id_ingrediente.nextval, 'ZANAHORIA', 'PIEZAS', 'PRESENTACION POR PIEZA', '-');
INSERT INTO INGREDIENTES VALUES (sq_id_ingrediente.nextval, 'APIO', 'PIEZAS', 'VARA', '-');
INSERT INTO INGREDIENTES VALUES (sq_id_ingrediente.nextval, 'TOMATE LICUADO', 'MILILITROS', 'TAZA', 'PURE DE TOMATE FRESCO');
INSERT INTO INGREDIENTES VALUES (sq_id_ingrediente.nextval, 'CALDO DE POLLO', 'MILILITROS', 'TAZA', 'LIQUIDO');
INSERT INTO INGREDIENTES VALUES (sq_id_ingrediente.nextval, 'TOMILLO', 'GRAMOS', 'GRANEL', 'HIERBA AROMATICA SECA');

-- RELACION: PLATILLO - INGREDIENTE

-- BROCHETA DE RES
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 1, 11, 1000); 
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 1, 9, 1);     
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 1, 16, 1);    
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 1, 7, 1);     
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 1, 15, 2);    
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 1, 17, 8);    
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 1, 18, 5);    
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 1, 19, 5);    

-- CHILES RELLENOS DE QUESO
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 2, 20, 4);    
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 2, 4, 500);   
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 2, 5, 2);     
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 2, 21, 10);   
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 2, 16, 1);    
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 2, 9, 0.5);   
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 2, 6, 100);   
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 2, 19, 5);    

-- FILETE MIGNON CON CHAMPINONES
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 3, 11, 1000); 
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 3, 12, 500);  
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 3, 13, 250);  
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 3, 14, 20);   
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 3, 1, 22.5);  
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 3, 22, 1);    

-- PESCADO AL VAPOR
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 4, 23, 1000); 
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 4, 24, 3);    
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 4, 25, 3);    
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 4, 16, 2);    
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 4, 8, 1);     
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 4, 26, 250);  
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 4, 9, 0.5);   
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 4, 10, 50);   

-- POLLO A LA CERVEZA
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 5, 1, 50);    
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 5, 2, 4);     
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 5, 3, 250);   
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 5, 27, 250);  
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 5, 28, 5);    
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 5, 21, 20);   
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 5, 19, 5);    
INSERT INTO PLATILLO_INGREDIENTE VALUES (sq_folio_pi.nextval, 5, 18, 5);    

-- INSTRUCCIONES (Utilizando el Procedimiento Almacenado)
BEGIN
    -- BROCHETA DE RES
    inserta_paso_receta(1, 1, 'CORTAR EN TROZOS DE 6x2 CM LOS FILETES, LA CEBOLLA, EL CHILE Y LA PIÑA.', 'PROCURAR TAMAÑO UNIFORME.');
    inserta_paso_receta(1, 2, 'SALPIMENTAR EL FILETE.', NULL);
    inserta_paso_receta(1, 3, 'INSERTAR ALTERNADAMENTE EN EL PALILLO UN TROZO DE CARNE, CHILE, CEBOLLA, TOMATE Y PIÑA.', 'REPETIR HASTA TERMINAR.');
    inserta_paso_receta(1, 4, 'MARCAR EN LA PLANCHA Y HORNEAR HASTA QUE SE COCINE LA CARNE.', 'VIGILAR PARA EVITAR QUE SE SEQUE.');

    -- CHILES RELLENOS DE QUESO
    inserta_paso_receta(2, 1, 'TATEMAR LOS CHILES Y PONERLOS EN UNA BOLSA.', 'DEJARLOS REPOSAR PARA QUE SUDEN.');
    inserta_paso_receta(2, 2, 'LIMPIAR LOS CHILES Y QUITAR LAS SEMILLAS.', 'CUIDAR DE NO ROMPERLOS.');
    inserta_paso_receta(2, 3, 'PARTIR EN CUADROS PEQUEÑOS CEBOLLA, TOMATE Y QUESO. AGREGAR SAL.', 'MEZCLAR BIEN.');
    inserta_paso_receta(2, 4, 'RELLENAR LOS CHILES CON LA MEZCLA.', NULL);
    inserta_paso_receta(2, 5, 'BATIR CLARAS A PUNTO DE LISTÓN, AÑADIR HARINA, SAL Y YEMAS.', 'MEZCLAR CON CUIDADO.');
    inserta_paso_receta(2, 6, 'CUBRIR LOS CHILES CON LA MEZCLA Y FREÍR.', 'HASTA DORAR Y LUEGO ESCURRIR.');

    -- FILETE MIGNON CON CHAMPINONES
    inserta_paso_receta(3, 1, 'REBANAR EL FILETE DE 1 PULGADA DE GROSOR Y SALPIMENTAR.', NULL);
    inserta_paso_receta(3, 2, 'ENROLLAR EL TOCINO ALREDEDOR DE LAS REBANADAS.', 'SUJETAR CON PALILLOS.');
    inserta_paso_receta(3, 3, 'FREÍR LA FÉCULA CON MANTEQUILLA HASTA OSCURECER.', NULL);
    inserta_paso_receta(3, 4, 'DISOLVER EL CALDO EN AGUA HIRVIENDO Y AÑADIR A LA FÉCULA CON CHAMPIÑONES.', 'HERVIR LIGERAMENTE.');
    inserta_paso_receta(3, 5, 'FREÍR LA CARNE AL TÉRMINO DESEADO.', '1/2, 3/4 O BIEN COCIDA.');
    inserta_paso_receta(3, 6, 'SERVIR Y BAÑAR CON LA SALSA.', NULL);

    -- PESCADO AL VAPOR
    inserta_paso_receta(4, 1, 'FILETEAR Y CONDIMENTAR CON SAL Y PIMIENTA EL PESCADO.', NULL);
    inserta_paso_receta(4, 2, 'CORTAR EN JULIANA LA ZANAHORIA Y EL APIO.', NULL);
    inserta_paso_receta(4, 3, 'LICUAR LOS TOMATES CON ORÉGANO Y SAL.', NULL);
    inserta_paso_receta(4, 4, 'MEZCLAR INGREDIENTES, AGREGAR ACEITUNAS Y HORNEAR.', 'DE 15 A 20 MINUTOS.');

    -- POLLO A LA CERVEZA
    inserta_paso_receta(5, 1, 'SOFREÍR LAS PECHUGAS EN MANTEQUILLA.', 'POR 8 A 10 MINUTOS.');
    inserta_paso_receta(5, 2, 'AGREGAR CERVEZA, CALDO Y CONDIMENTOS. MEZCLAR.', NULL);
    inserta_paso_receta(5, 3, 'TAPAR Y COCINAR A FUEGO LENTO.', 'POR 45-50 MINUTOS.');
    inserta_paso_receta(5, 4, 'MEZCLAR 2 CDAS DE MANTEQUILLA DERRETIDA CON HARINA Y APARTAR.', NULL);
    inserta_paso_receta(5, 5, 'SACAR EL POLLO Y AGREGAR LA MANTEQUILLA AMASADA A LOS JUGOS.', NULL);
    inserta_paso_receta(5, 6, 'COCINAR REVOLVIENDO HASTA QUE ESPESE LA SALSA.', NULL);
    inserta_paso_receta(5, 7, 'BAÑAR EL POLLO CON LA SALSA Y SERVIR.', NULL);

    COMMIT;
END;
/